### ISSUE TITLE
crash on start up.

### ISSUE THREAD

**Issue by KaeminMoore** [baffler/Transparent-Twitch-Chat-Overlay#1]
Problem Event Name:	CLR20r3
  Problem Signature 01:	TransparentTwitchChatWPF.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5b109aa7
  Problem Signature 04:	CefSharp.Wpf
  Problem Signature 05:	57.0.0.0
  Problem Signature 06:	58f5a7be
  Problem Signature 07:	82
  Problem Signature 08:	18
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by baffler** [comment]
If you don't mind, can you get the [latest release v0.5](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.5). It should pop up a message box with a lot more information. You can click on the message box to make sure it's focused and press Ctrl+C and copy the entire message there (no need to highlight anything, all the text will be copied regardless).

**Comment by baffler** [comment]
If you don't mind, can you create a new issue and give some examples of games it's not working well with? I'll do some testing and see if I can fix the issue. For now, you could try using using the custom chat url, it's under settings. You can google kapchat or restream.io and change the settings/themes for those and just copy/paste the url they give you. Those urls are typically used with OBS but they also work with my program as well. However, I'll make it easier to change the font/theme in the program itself in the next update I release.

**Comment by baffler** [comment]
You can change more settings in v0.6. If you're still having a crash issue, feel free to reopen issue.
