### ISSUE TITLE
Ignore Specific users/bots

### ISSUE THREAD

**Issue by Boymann** [baffler/Transparent-Twitch-Chat-Overlay#10]
The overlay ignores !commands, but would be nice if we could ignore specific users, or bots to avoid spam on screen and be more focused on the viewers I think.

**Comment by baffler** [comment]
I think it's something that is out of scope of this project. The way the app works is it loads a chat from a website, the default one is KapChat which is meant for OBS widget for chat. You can enter a custom URL in the settings and use any chat widget (typically meant for OBS) and it will work, so if there's a chat widget that does what you suggested, then you could use it with the app.

**Comment by baffler** [comment]
If you want this functionality, you should be able to use this chat from streamlabs
https://streamlabs.com/dashboard#/chatbox

It has a way to hide bots, !commands, and lets you mute users by adding their name to a list. Just set my program to use a custom URL. In v0.6 it's in settings window, then bottom left just check "Custom URL". And set the URL you copy for the chat widget there in the first text box.
