### ISSUE TITLE
Detection as Virus by multiple vendors, all versions of Software

### ISSUE THREAD

**Issue by 1215drew** [baffler/Transparent-Twitch-Chat-Overlay#11]
Within the archive downloaded from the releases section for version 0.5, the main assembly is getting picked up by 8 antivirus suites as being a variant of Ursu, a very new ransomware and C&C malware:
https://www.virustotal.com/#/file/1a5c9d984eeab3722b49d3b0d1221bdcde931a719cef8b35f507b68b5f0e4f7e/detection

![transparenttwitchchatoverlay_malware](https://user-images.githubusercontent.com/32055840/48229998-7722cb00-e35e-11e8-9b13-53b2bb18a8e1.png)

Version 0.4 gets picked up by 17 suites as being either the same variant of Ursu or some other malware: https://www.virustotal.com/#/file/67e43ae1c60fadbd48bc305e025887cfa47875a2f890ebae50872f8786ac7200/detection

As well as Version 0.3, which gets picked up by 22 suites as being some form of malware
https://www.virustotal.com/#/file/ffc3ed02a1c6995be2ecd7aa726e5bb66edcd986101436dded68101949611ae3/detection

This is a concerningly high number of detections.

**Comment by baffler** [comment]
I'll do some research on how to prevent false positives. There's no malware that was intentionally added, but I don't think Ursu is something that can embed itself into executables, at least I've never had any detection of Ursu on my machine and I'm using Windows Defender (which says it does detect Ursu). From what I can tell, it's related to some generic detection virus sites will use, but it seems there are ways to help prevent false positives, I'll look into this for next release.

**Comment by 1215drew** [comment]
Yeah I ran it through virustotal since bitdefender picked it up on my local
machine. Looking through source, I was expecting perhaps an IRC issue as a
lot of malware uses IRC for C&C; but you're just using a browsercontrol
which makes this even weirder.

**Comment by puyanwei** [comment]
Is there any way to bypass this? After reinstalling Windows I'm unable to open this anymore

**Comment by baffler** [comment]
@puyanwei If it's the "Windows protected your PC" message (which is the Windows Defender Smart Screen). You'll need to click "More info" and then "Run anyway". You'll only have to do this the first time you launch it.

If it's something else, what error or message do you see?

**Comment by maryjane9110024** [comment]
I have this same thing happen with BitDefender. It blocks it and removes it. I put it on a "safe list" and then I get an error and it won't let me unzip the exe

**Comment by baffler** [comment]
Didn't realize some antivirus was actually blocking it. I'll look into this for next release, I'll have to get BitDefender and see if I can prevent it from picking up the false positive for the app.

**Comment by unRyker** [comment]
A polite reminder that this issue should be closed. VirusTotal gives 0.7 a perfect score: https://www.virustotal.com/gui/file/d8507b7fc3dad8218be29129fc9797ceefcf32e472a09fe70e5069be290bd16b/detection
![image](https://user-images.githubusercontent.com/26333062/92136795-7502e980-edda-11ea-8f04-92dbbc42d84a.png)
