### ISSUE TITLE
Border

### ISSUE THREAD

**Issue by bonkina** [baffler/Transparent-Twitch-Chat-Overlay#112]
been having the issue where i can't toggle the borders back on, it's not giving the option in the taskbar.

**Comment by Portaluke** [comment]
I have 2 solutions as a workaround.
1) Click on the item in the taskbar and then hit F9. (This brings the app into focus and allows the F9 key to work)
2) Right click on the Tray icon (left of the clock, may need to be expanded) and select "Hide/Show Border (F9)"
![fVQ15cBMa2](https://user-images.githubusercontent.com/58648868/194719923-1b6c883f-d317-4922-ba8a-66a214591aa2.png)

As far as the Taskbar issue goes, I currently have the same issue with those options not showing up on right click.
![zAcHSCgu6b](https://user-images.githubusercontent.com/58648868/194719957-b78a49e4-a4ba-4def-ae52-914aa6602eec.png)
