### ISSUE TITLE
Add current viewer count

### ISSUE THREAD

**Issue by ddstevens** [baffler/Transparent-Twitch-Chat-Overlay#13]
Is it possible to add viewer count as well as the number of people in chat?

**Comment by baffler** [comment]
If there's any type of widget (like from streamlabs/streamelements/etc) that can do this, you can now add a new window in v0.6 and have this displayed.

**Comment by ddstevens** [comment]
Using the streamlabs viewer widget worked perfectly with the new window functionality.  Thanks!
