### ISSUE TITLE
7tv emotes not showing up

### ISSUE THREAD

**Issue by Azrilkai** [baffler/Transparent-Twitch-Chat-Overlay#133]
I'm using the pre-release version 0.9.2 and it's still not working, https://i.imgur.com/RZq2y9P.png the 3rd emote used there is from BTTV just so show a comparison.

**Comment by baffler** [comment]
If you go into the settings and click "Chat" on the left side, then look at the bottom-left, there's a setting to change the type of chat used. You can change it to jChat and it will have the 7tv emotes enabled for that one
