### ISSUE TITLE
Incompatibility issue - overlay not shown on obs classic

### ISSUE THREAD

**Issue by talex9** [baffler/Transparent-Twitch-Chat-Overlay#143]
Hi!

I'm having an issue where the overlay is not being shown on obs classic portable v0.659b and it giving me a 'cannot find window' message when trying to capture it as a window (despite it showing it on the windows list) and also not being shown on the monitor capture either, though it can be seen on the desktop normally and it works without issues on the operative system. It's just obs not seeing it.

Nevertheless, this worked a couple of weeks ago -but only on the capture windows mode, not on the capture monitor mode- and the whole has worked before with this software, but on a different hardware, which leads me to suppose the incompatibility is with the video card, rather than the software itself. I now have a computer with an Nvidia quadro 1800m and i believe the moment when it was working with 'window capture' mode was prior to a recent update of the video drivers to its latest.

I am thankful for any assistance on this situation.

**Comment by ProjectXsent** [comment]
Were you planning to use the app as chat overlay on OBS?

**Comment by talex9** [comment]
It doesn't look bad, but i can't see that on the same screen while playing, right? That's one of the biggest advantages on twitch chat overlay, it allows me to do everything on a single monitor. Nonetheless, if i can't make it work out, this will definetly come in handy. Appreciated!!

**Comment by ProjectXsent** [comment]
> It doesn't look bad, but i can't see that on the same screen while playing, right? That's one of the biggest advantages on twitch chat overlay, it allows me to do everything on a single monitor. Nonetheless, if i can't make it work out, this will definetly come in handy. Appreciated!!

Ahhhh make sure that the display setting of the game that your playing is on Borderless and Twitch Chat Overlay will always be on top.

**Comment by talex9** [comment]
No, it's not that, i always try to play with windowed mode just in case...but it doesn't even show on plain desktop!

Also, i tried the window capture by mere luck, because before i used it without that, and it worked, but on this particular hardware, it needs that to work...or at least it needed that the time it worked.
