### ISSUE TITLE
Doesn't work with Cyberpunk 2077 properly

### ISSUE THREAD

**Issue by Ivonilsonx** [baffler/Transparent-Twitch-Chat-Overlay#146]
Cyberpunk 2077 is bordeless, when i open the game the overlay works, if i alt-tab it doesn't work anymore, i have to close and open the whole game for the overlay to work again

**Comment by DANGER-007** [comment]
Run as administrator

**Comment by shoogo242** [comment]
I have the same problem, running the overlay twitch app as administrator doesnt fix the problem for me.

**Comment by baffler** [comment]
See #170 I might have a fix for this soon.
