### ISSUE TITLE
I'd like to filter OUT a username...

### ISSUE THREAD

**Issue by Sn0uu** [baffler/Transparent-Twitch-Chat-Overlay#147]
I see that I can filter to ONLY show a specific list of people or highlight a list of users, and there's an option to show bots yes/no, however, my bot isn't registered as a bot (I just use my alt account) so it can't be filtered out :(
Could you please have 3 different lists? A show only, a hide only, and a highlight only list?

**Comment by StephenIz** [comment]
If you use the Twitch Popout option, I believe you can blacklist specific usernames through the "Blacklist Keywords" section in the BetterTTV settings.

**Comment by baffler** [comment]
I believe the latest versions is setup to what you're asking for. There is filtering by select usernames only, you can switch to having it highlight select usernames, and there's a block names list now so you can block bots that you don't want showing up.
