### ISSUE TITLE
SOURCE OF ACTIVITY/RECENT EVENTS.......

### ISSUE THREAD

**Issue by LianCta** [baffler/Transparent-Twitch-Chat-Overlay#148]
For 5 months the application has presented me with a problem to generate the recent events window of Twitch or streamlabs

I tried updating the app but it keeps happening. 

when displaying the creator window URL, It does not allow me to access my account even though I enter it correctly

This problem is also presented by more people from Latin America who occupy the APP (I saw it in comments of videos that this app recommends). sorry if my english is still not that good and that prevents correct communication

![Sin título](https://user-images.githubusercontent.com/118103606/201515340-802c45bb-8723-4412-bb8f-b8696e49f79d.png)

**Comment by baffler** [comment]
See #139
