### ISSUE TITLE
Comments as they appear in Twitch

### ISSUE THREAD

**Issue by sigvardbjorkman** [baffler/Transparent-Twitch-Chat-Overlay#149]
I wonder why the comments appear at the top in this application window when they actually appear at the bottom in Twitch? I'd rather have the comments appear at the bottom of the window and then be shoved upwards, as is actually the case in Twitch.

**Comment by sigvardbjorkman** [comment]
For this reason I now switched from the default to the Twitch one but, it displays an accept cookies thing that doesn't go away when clicked. Any way to solve this issue as well? 
![image](https://user-images.githubusercontent.com/117851974/202911774-56eb31bf-f531-4b54-9ae1-1db36d3e07aa.png)

**Comment by obvSweet** [comment]
I'm pretty sure that's a feature of KapChat and also originally a feature of twitch chat. On the desktop site: as your screen becomes fully populated with messages, new ones will appear at the bottom and push older messages upward. 

However with KapChat, individual messages on twitch chat will fade out and the lines are removed entirely after fade out; so if your fade out time is very short, or your twitch chat is chronically empty, your messages will reappear starting from the top.

You can test this yourself by going to an empty channel and spamming a several lines of chat.
*ForeverAlone*
