### ISSUE TITLE
resizing in windows 10

### ISSUE THREAD

**Issue by lolicage** [baffler/Transparent-Twitch-Chat-Overlay#15]
dragged the chat window to the top corner of my screen, and it resized to fullscreen.
it is now impossible to move via the black bar and the resizing thing on the bottom right does not exist anymore.

reinstalling does not reset settings, and documentation does not tell me where settings are stored.
while in fullscreen, chat on the top left blocks ability to click things underneath it.

**Comment by baffler** [comment]
Thanks for the feedback. v0.6.1 will fix this issue. It will let you double click the black border to return the window to normal (un-maximize it). Just in case, I added a way to reset the window as well, see the screenshot on where to find that. It will also ask if you want to open the settings folder when you reset the window.

https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.6.1

![2018-11-26_18-45-47](https://user-images.githubusercontent.com/1980600/49049280-62429600-f1ac-11e8-8e6f-476b76c208a1.png)
