### ISSUE TITLE
Can't add event widget

### ISSUE THREAD

**Issue by quaffle13** [baffler/Transparent-Twitch-Chat-Overlay#151]
Hi, an error occurs whenever I add a widget from streamlabs it causes the app to crash since the URL from streamlabs is very long and the app only accepts a certain amount of characters. Please fix. Thank you!
![image](https://user-images.githubusercontent.com/99308008/207898158-db8c8221-a6df-4028-b425-a3c16557d402.png)

**Comment by BJ0b1** [comment]
Can't add event widget , activity feed streamelements and streamlabs say Your browser is not currently supported. Please use a [recommended browser]

**Comment by MrBaynie** [comment]
For me widgets work with streamelements, but streamlabs widgets are still broken.

**Comment by amphibianimbus** [comment]
Same here. Streamelements windows open just fine but streamlabs widgets show me the same message

**Comment by baffler** [comment]
This should be fixed now with the latest versions
