### ISSUE TITLE
Doesn't run as of 1/9/2023, no installer found

### ISSUE THREAD

**Issue by LoganCTanner** [baffler/Transparent-Twitch-Chat-Overlay#153]
Stopped working as of 1/9/2023, ran as administrator & didn't work. Changing usernames didn't work.

Tried uninstalling & reinstalling, no installer can be found

**Comment by LoganCTanner** [comment]
mb found the installer, retrying now

**Comment by LoganCTanner** [comment]
didn't work when I tried: deleted app data, reinstalled, ran as administrator, reran as regular user

don't know how to compile from source, but noticed Newtonsoft.json was updated to 13.x.x from 12.x.x

**Comment by baffler** [comment]
You can try v0.93, just released it. It has the Newtonsoft update
