### ISSUE TITLE
Cannot find Channel ID

### ISSUE THREAD

**Issue by FKWafc** [baffler/Transparent-Twitch-Chat-Overlay#154]
When I type in my Username and select 'Get Channel ID' I see this error message. 

![Screenshot (14)](https://user-images.githubusercontent.com/45898924/211354746-2d92fd0e-e165-4b78-8e60-271141a8e117.png)

I might be doing something wrong, but this was after a fresh install. So I hadn't messed with any of the settings. I tried with v0.92 and v0.91 and experienced the same issue with both. I have also tried running the program as administrator to no avail.

**Comment by Mashkaronus** [comment]
Got same problem today.

**Comment by Gnibily1** [comment]
I have tried several ways to get my chat stream tied into this, i get same error as seen above no matter what brouser or method used, even generated codes are not working when supplied by twitch and chrome converters. If caht cant be tied to this app whats its purpose?

**Comment by LoganCTanner** [comment]
> I have tried several ways to get my chat stream tied into this, i get same error as seen above no matter what brouser or method used, even generated codes are not working when supplied by twitch and chrome converters. If caht cant be tied to this app whats its purpose?
> 

It was working yesterday. It's probably just a dependency that's out of date. Dependabot recommended a new commit with "Newtonsoft.json" being updated to the most recent version, which most likely means whatever code relying on newtonsoft is either incompatible with version 13.x.x and then doing nothing or it's trying to use a deprecated resource and then doing nothing. It looks like newtonsoft is a json framework & I'm just speculating, w/o reading source code, that it's responsible for handling the messages that come from twitch/YT which would result in not even the connection message displaying

**Comment by baffler** [comment]
For now I've linked to this url from within the app: https://www.streamweasels.com/tools/convert-twitch-username-to-user-id/

There's also a Chrome and Firefox extension you can get, the github has the links to them:
https://github.com/swiftyspiffy/Twitch-Username-and-User-ID-Translator

Hopefully I can get it working within the app completely again, but for now you'll have to use other tools. Just copy/paste the ID into the box for Channel ID
