### ISSUE TITLE
Cannot Click Twitch Overlay's "Proceed" Button

### ISSUE THREAD

**Issue by benamation** [baffler/Transparent-Twitch-Chat-Overlay#155]
![Screenshot 2023-01-11 192659](https://user-images.githubusercontent.com/6165172/211968868-1cb73a4d-c56b-4fe8-8e81-1ba081c54835.jpg)

These twitch messages have appeared for me and when I click "Proceed" to dismiss them, nothing happens.

**Comment by baffler** [comment]
Are you able to use jChat instead? I'm possibly going to have to drop support for the Twitch Popout, because Twitch has dropped support for anything except the major browsers.

**Comment by baffler** [comment]
See #164
