### ISSUE TITLE
Unable to accept cookies

### ISSUE THREAD

**Issue by Solarcinaire** [baffler/Transparent-Twitch-Chat-Overlay#156]
![image](https://user-images.githubusercontent.com/122544698/212096107-c5492389-4442-466c-ab48-ec233ebe9387.png)
Can click on Manage cookies, but no matter what I do it is unable to accept cookies and for the purple background to disappear.

**Comment by fbrinker** [comment]
I have no idea about coding with c# and net. Would it be possible to use the edge / chromium engine as browser? Maybe directly within windows? Or faking the browser headers otherwise? :)

**Comment by baffler** [comment]
See #164
