### ISSUE TITLE
Idea: with a specific hotkeys, which will show a type box. We can reply to chat then hide it and back to the game after sending messages.

### ISSUE THREAD

**Issue by Bakabot307** [baffler/Transparent-Twitch-Chat-Overlay#160]
since you dont want to tab out to read chat why not YEPPERS

**Comment by baffler** [comment]
So this is possible now with [v1.0.0](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.0). If you change the chat type to Twitch Popout, login to Twitch, and use the global hotkeys, you can press the F7 key and it will enable chatbox interaction, type what you want, and press F7 again to disable the interaction with the chatbox.
