### ISSUE TITLE
Crash on startup app

### ISSUE THREAD

**Issue by Alucabr** [baffler/Transparent-Twitch-Chat-Overlay#178]
---------------------------
Click on this message box and press Ctrl-C to copy the entire message
---------------------------
An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.

System.Windows.Markup.XamlParseException: A invocação do construtor no tipo 'TransparentTwitchChatWPF.MainWindow' que corresponde às restrições de associação especificadas iniciou uma exceção. ---> System.IO.FileNotFoundException: Não foi possível carregar arquivo ou assembly 'CefSharp.Core.Runtime.dll' ou uma de suas dependências. Não foi possível encontrar o módulo especificado.

   em CefSharp.CefSettingsBase..ctor()

   em CefSharp.Wpf.CefSettings..ctor()

   em TransparentTwitchChatWPF.MainWindow..ctor()

   --- Fim do rastreamento de pilha de exceções internas ---

   em System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   em System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   em System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   em System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   em System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)

   em System.Windows.Application.DoStartup()

   em System.Windows.Application.<.ctor>b__1_0(Object unused)

   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   em System.Windows.Threading.DispatcherOperation.InvokeImpl()

   em System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   em MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   em MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   em System.Windows.Threading.DispatcherOperation.Invoke()

   em System.Windows.Threading.Dispatcher.ProcessQueue()

   em System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   em MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   em MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   em System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   em MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   em MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   em System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   em System.Windows.Application.RunDispatcher(Object ignore)

   em System.Windows.Application.RunInternal(Window window)

   em System.Windows.Application.Run(Window window)

   em System.Windows.Application.Run()

   em TransparentTwitchChatWPF.App.Main()
---------------------------
OK   
---------------------------

**Comment by leonflint** [comment]
I have had this since the 16th of August.

![image](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/assets/126466018/caa4ae95-2d0f-4646-b57d-80fe3f20a165)

You might want to change the title to something more descriptive, like

> System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.Runtime.dll' or one of its dependencies
