### ISSUE TITLE
Suggestion: Channel Points

### ISSUE THREAD

**Issue by lol2121212** [baffler/Transparent-Twitch-Chat-Overlay#179]
Add an option to make a noise when someone uses channel points

**Comment by baffler** [comment]
[v0.9.5](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.9.5) has better support for channel points, and it should make a sound as well, though it is the same sound as the other chat messages. Are you wanting a different sound for just channel points?
