### ISSUE TITLE
WoW

### ISSUE THREAD

**Issue by shamanstu** [baffler/Transparent-Twitch-Chat-Overlay#18]
Apparently the new patch in World of Warcraft doesn't like overlays.  The advice on this per Blizzard it to get the most recent version of whatever you are using for an overlay.

**Comment by baffler** [comment]
It should work, I've just tested it and there doesn't seem to be any issue. Can you provide more info? What version of the program, windows version? You're also talking about the live WoW version and not PTR right?

**Comment by shamanstu** [comment]
To be fair, not using the TranparentChat program only made the problem much more infrequent. Yes, live WoW 8.1.5.29718
Win 10 build 17134

**Comment by shamanstu** [comment]
Should the issue come up again, I believe I found the fix.  In advanced settings select Directx 11 vs Directx 12.  Thanks for the great program!  -Stu

**Comment by baffler** [comment]
Thanks for letting me know. Glad it's working for you.
