### ISSUE TITLE
jChat: Fade does not affect initial connection status messages

### ISSUE THREAD

**Issue by HeyoImPink** [baffler/Transparent-Twitch-Chat-Overlay#182]
When using jChat with the option to fade messages after a period of time, chat messages will disappear but the intial "Loading... jChat: Connecting to IRC server..." etc. messages will remain on screen permanently.

**Comment by baffler** [comment]
This is fixed with latest version [v0.9.5](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.9.5)
