### ISSUE TITLE
window always toggles off 

### ISSUE THREAD

**Issue by gspooks** [baffler/Transparent-Twitch-Chat-Overlay#186]
the window border always toggles off I cannot change settings or toggle back on, if I use the taskbar and right click for the options to toggle the border or use settings it just opens another instance of the program.
I have tried doing a clean install but when I reinstall the chat loads connected to my twitch account.
does it save settings anywhere other then the install folder location?

**Comment by Mantikorit** [comment]
I encountered the same problem a few hours after installation. After the complete removal, I decided to do a full search for this program and found one folder with the cache and settings.
The folder is called **_TransparentTwitchChatWPF_** and is located in `C:\Users \...\AppData\Roaming\`.
You can search for a specific file that interferes with or delete this entire folder. If you delete a folder, I advise you to write down its location somewhere to re-solve this problem and all the data for quick recovery of settings.

**Comment by baffler** [comment]
[v0.9.5](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.9.5) will do a clean uninstall now. It will remove all the settings associated with the app.
