### ISSUE TITLE
Widget URL is too long

### ISSUE THREAD

**Issue by LitraFrance** [baffler/Transparent-Twitch-Chat-Overlay#192]
When i put my streamlabs widget url it says me that the url is to long so i cant see my alerts on my screen.

**Comment by LitraFrance** [comment]
Please fix it so we can put a more long link

**Comment by baffler** [comment]
You might be using an older version, there was a fix for this in the newest versions. https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases
