### ISSUE TITLE
Browser not suported.

### ISSUE THREAD

**Issue by IndioBR** [baffler/Transparent-Twitch-Chat-Overlay#194]
Adding a widget, i tried to log in on twich and this message shows up.
![image](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/assets/88745612/86c9939d-9da8-41df-b505-515ab9278011)

**Comment by baffler** [comment]
Can see issue [#139](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/issues/139) about this. From what I've researched, Twitch put in measures for security reasons (supposedly to stop bots) to prevent Chromium from being used to login to Twitch. I have yet to find a workaround for this.

**Comment by baffler** [comment]
Next version will have a fix for this. Will be switching to WebView2, which is sort of like Edge.

**Comment by baffler** [comment]
[v.0.10.0](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.10.0) has a fix for this
