### ISSUE TITLE
Trouble Connecting to Twitch Chat

### ISSUE THREAD

**Issue by meystx** [baffler/Transparent-Twitch-Chat-Overlay#20]
Hello! For the last few months I've had trouble connecting to twitch. It extremely rarely works although there are periods where I do manage to connect. However it is very inconsistent. I am not sure what could be causing this issue? I was using this app without issue for a few weeks until this started happening, then I began having issues end of last year and am now still rarely able to connect.
I've tried multiple things such as changing capitalization on my twitch user name, deleting the settings folder, removing the program & reinstalling but I am always met with the same issue.

Do you know what could be causing this? As it's extremely frequent and has been going on for a few months it might not be twitch related as there is only 1 other complain about a similar thing, which seems to have resolved itself.
I would appreciate any help

Thank you

**Comment by baffler** [comment]
Very late reply but if there's some issue with it not showing the chat at all, it would have to be something either wrong with KapChat or just some problem you're having in general with Twitch itself. If the chat on twitch.tv works fine, then I'd suggest trying another chat widget (any chat widget made for OBS will work) and then use the Custom URL setting to switch it to that chat.
