### ISSUE TITLE
Built in Text Edit

### ISSUE THREAD

**Issue by SingStarAt60Frames** [baffler/Transparent-Twitch-Chat-Overlay#213]
There's got to be a settings file or something somewhere that will let me edit the text size and type locally. 
This plugin for the text is still too awkward to use and it can't be adjusted to the size I want. 
Can I locally change text size and window settings?

**Comment by wailytv** [comment]
Came here looking for the same thing. I use this frequently but a couple of days ago the font changed to one bigger and outlined which I don't like. I tried every theme but it keeps getting bigger and outlined with transparent fill. It would be great if we had a couple of font choices and different sizes

**Comment by baffler** [comment]
I can possibly make it easier to change the font type (right now you could change it with CSS). But if you need the size adjusted, just show the borders, click the menu at the top-left and change the Zoom level to what you need. It should save the setting too and activate it for each session.
