### ISSUE TITLE
doesnt work on cyberpunk

### ISSUE THREAD

**Issue by R0yPlays** [baffler/Transparent-Twitch-Chat-Overlay#214]
basically doesnt work on cyberpunk 2077. as soon as game opens up it goes away.

https://github.com/hperrin/stream-overlay this project works on cyberpunk so maybe check it out but know that twitch's own alert box doesnt work on it only streamelements and streamlabs ones do.

**Comment by baffler** [comment]
Can you try out [v1.0.0](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.0) and see if it fixes the issue. It adds global hotkeys and you may have to press the F8 key, which will force the app to be put on top, note that you may have to press F8 each time you alt-tab out and back into the game.
