### ISSUE TITLE
Start with borders disabled

### ISSUE THREAD

**Issue by uros76** [baffler/Transparent-Twitch-Chat-Overlay#22]
Hi. Is there a way to save setting to start the app with borders off? Each time app runs I need to toggle borders.

**Comment by Boymann** [comment]
Hey, I'm almost a year late on this, but did you find anything that made it start with borders off? @uros76 Maybe anyone else? I would also like to know if that would be possible.

**Comment by uros76** [comment]
Hi. No, I did not find a solution. I have to click that top button every time to hide the borders :/

**Comment by baffler** [comment]
I can add this in the next update. I plan on updating soon™

**Comment by baffler** [comment]
It's in [v0.7](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.7). Thanks for the suggestion 👍
