### ISSUE TITLE
Overlay over Minecraft?

### ISSUE THREAD

**Issue by VaikusGames** [baffler/Transparent-Twitch-Chat-Overlay#220]
Hi! I'm not sure if its a minecraft thing or a fullscreen thing but I was trying to use the Twitch overlay over the minecraft game but it was not overlaying the top of the fullscreened game. It works when i do not have it fullscreened and have it windowed.

**Comment by Rofii** [comment]
I was having the same problem. This fixed it for me. It makes the game full-screen but it still behaves as if it is in windowed mode, so overlays appear on top. https://github.com/Codeusa/Borderless-Gaming
