### ISSUE TITLE
Unable to login to Twitch: "Browser not Supported"

### ISSUE THREAD

**Issue by GatK0ng** [baffler/Transparent-Twitch-Chat-Overlay#228]
Unable to login to Twitch via the Twitch Chat Overlay: "Browser not Supported"

My PC default browser is Firefox, and I can log into Twitch from that without issue.

What browser is the Twitch Chat Overlay appearing to be to Twitch that Twitch doesn't support it?

Can the "default browser" for the overlay be configured?

Thank you.

**Comment by GatK0ng** [comment]
v0.10.0 does allow sign-in with Twitch.

A couple minor issues to report:
1. After first launching, the overlay is not transparent, but is opaque white and not adjustable. I messed with some settings (sorry, I can't recall my exact steps), saved it, and then transparency was functioning as intended, and also becomes adjustable + and -.
2. Setting/General/"Allow Mul**it**ple Instances (beta)" should read "Allow Mul**ti**ple Instances (beta)"

Thanks for your prompt reply.  :)

**Comment by GatK0ng** [comment]
Another issue: if you hide borders, not only is the upper-right-hand "x" not interact-able, neither is the Twitch "Send a message" text box, so you can't reply to the Twitch chat while the overlay border is hidden.

**Comment by baffler** [comment]
> v0.10.0 does allow sign-in with Twitch.
> 
> A couple [edit: three] minor issues to report:
> 
>     1. After first launching, the overlay is not transparent, but is opaque white and not adjustable. I messed with some settings (sorry, I can't recall my exact steps), saved it, and then transparency was functioning as intended, and also becomes adjustable + and -.

Seems there was some issue with the background color property. I think I may have fixed this with the latest release [v1.0.0](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.0) if you want to try it

>     2. Setting/General/"Allow Mul**it**ple Instances (beta)" should read "Allow Mul**ti**ple Instances (beta)"
> 
>     3. [edit to add] No desktop shortcut is automatically made (did I miss an option tic-box?).

[v1.0.0](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.0) will also let you install it and create a desktop shortcut. This is a new installer though, so you might have to uninstall any older versions first, manually.

**Comment by baffler** [comment]
> Another issue: if you hide borders, not only is the upper-right-hand "x" not interact-able, neither is the Twitch "Send a message" text box, so you can't reply to the Twitch chat while the overlay border is hidden.

In v1.0.0, I put in global hotkeys, and you can now press F7 to quickly interact with the app, so you'd be able to press the "x" or send a message on twitch after pressing F7, then just press F7 again to make it non-interactable.
