### ISSUE TITLE
Support Mixer Chat ?

### ISSUE THREAD

**Issue by moanatari** [baffler/Transparent-Twitch-Chat-Overlay#23]
Hey!
Are you going to adapt your software to work with Mixer?
I used it a lot with Twitch I only have one screen, it was really convenient!
Otherwise thank you for your software it is top!

**Comment by baffler** [comment]
If you use any overlay for OBS to show your mixer chat, just use that same exact URL in my program. Make sure you have the latest release and open settings. At the bottom of the settings window check the box for Custom URL, then just paste the URL there.

If you don't use any chat overlay for OBS, you could try this one, it works for me with my app:
https://crowbartools.com/tools/chat-overlay/

![image](https://user-images.githubusercontent.com/1980600/64172607-5c58a000-ce23-11e9-8e40-6f04ca677c4f.png)

Should look like this. For this particular chat overlay, it's not very transparent so I put in custom CSS to make the background more transparent (you can leave it out if you don't want it).

`.chatmessage { background-color: rgba(0,0,0,0.4); }`

**Comment by baffler** [comment]
Also, I will probably end up making this easier in the settings to add mixer, similar to the way you can add the Twitch chat easily right now.

**Comment by Snugglesffxi** [comment]
omg i would love this so much (i mean i already do for twitch) but I would love it if we could have both chats connected. the restream multichat lacks basic settings required that this app perfects. Any chance we'll have multichat integration? 💃

**Comment by NickParks** [comment]
I went ahead and forked the repo and added some Mixer features (I did remove the Twitch ones however).

It's pretty basic but it gets the job done if you're still looking for a util.

**Comment by Snugglesffxi** [comment]
> 
> 
> I went ahead and forked the repo and added some Mixer features (I did remove the Twitch ones however).
> 
> It's pretty basic but it gets the job done if you're still looking for a util.

does it do both at the same time? 🐙

**Comment by NickParks** [comment]
> > I went ahead and forked the repo and added some Mixer features (I did remove the Twitch ones however).
> > It's pretty basic but it gets the job done if you're still looking for a util.
> 
> does it do both at the same time? 🐙
> edit nvm i misread that. Yeah I'm looking for something i can do both at the same time!
> 
> edit2: I tried it, this lacks all of the good things about transparent twitch chat overlay. 1, its not transparent or doesn't have settings for that (where exactly do you place this on your game window?) also no settings to change the style or timeout delay so messages won't stay static forever. If it works for you great, but imma just wait for baffler, thanks!

The actual "overlay" is just a webpage. Just built out a basic version, I won't include support for both in mine but I do plan on fixing the transparency issue tomorrow. Just wanted to push out something tonight :).

**Comment by Snugglesffxi** [comment]
> The actual "overlay" is just a webpage. Just built out a basic version, I won't include support for both in mine but I do plan on fixing the transparency issue tomorrow. Just wanted to push out something tonight :).

might be usable if transparent but no option for message timeouts is trouble, the box would be filled with old messages. if it had that i'd use the one for twitch and one for mixer haha

**Comment by baffler** [comment]
I guess we don't need mixer chat anymore since Microsoft is closing it down. RIP
