### ISSUE TITLE
Don't Bind Things To F9 Key

### ISSUE THREAD

**Issue by GT500org** [baffler/Transparent-Twitch-Chat-Overlay#231]
F9 is the old Fraps record video key, and I still use it as my video record key in almost every video recording application I use (other than OBS Studio).

It's really not good to have permanent keybinds regardless, as you never know what third-party software they may conflict with.

**Comment by baffler** [comment]
Didn't realize the global hotkeys would prevent other apps from using that same hotkey. I've updated in [v1.0.1](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.1) to default adding Ctrl+Alt to all the keybinds, and you can now change them in the Settings under General.

**Comment by GT500org** [comment]
Awesome, thanks.

Also, it's not so much that it would prevent other apps from using the same hotkey and more that both apps would respond when the key is pressed.
