### ISSUE TITLE
Hide the close button (x) in the top right corner of the window when not interactive/borders are off.

### ISSUE THREAD

**Issue by dethzord** [baffler/Transparent-Twitch-Chat-Overlay#239]
### Discussed in https://github.com/baffler/Transparent-Twitch-Chat-Overlay/discussions/238

<div type='discussions-op-text'>

<sup>Originally posted by **dethzord** February 11, 2024</sup>
The new version(s) (I just upgraded tonight) now leaves the "x" icon displayed for closing the window, even when the window is not interactive and the border is hidden.  Screenshot attached.  Note that the "x" shows even if the chat is quiet/blank.  I added a chat message just to make things stand out.

![hovering x](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/assets/24793681/d49761cb-0af6-4619-a44c-31fb0c7677f2)
</div>

**Comment by baffler** [comment]
You can read more about it on this issue #235. Closing due to duplicate
