### ISSUE TITLE
The 'X' button does not disappear anymore (after the new update)

### ISSUE THREAD

**Issue by VinylNix** [baffler/Transparent-Twitch-Chat-Overlay#242]
So I'd been using the older version for quite a long time and never had this issue with the X (for closing the window) not disappearing after you clear the interface. Now it looks like this (it always shows over all apps):

![image](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/assets/9739129/3bf4cff5-6477-471f-9944-1b311c26bfe6)

Is there a way to make it invisible like in the previous version?

Also, after installing the new version all the settings got reset.

**Comment by OGNetheri** [comment]
I'm having the same annoyance on  1.0.2.  

![image](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/assets/110769602/f137051f-8282-483d-9e00-f60b23e02c8e)

**Comment by DerrPHANTOM** [comment]
I have also noticed this issue and have reverted back to the old version, as I cant stand it.

**Comment by baffler** [comment]
This is fixed in [v1.0.4](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.4)
