### ISSUE TITLE
OBS not recording program?

### ISSUE THREAD

**Issue by Dragon911XX** [baffler/Transparent-Twitch-Chat-Overlay#25]
I'm trying to record the transparent window for OBS, but it seems to just be a black screen.

**Comment by Zariwey0** [comment]
I think you should use 'Display Capture' to show the chat in your streaming/recording. I tried other ways but did not work for me.

**Comment by baffler** [comment]
If you want to record the chat, go to https://nightdev.com/kapchat and set it up from there. Add a browser source in OBS and put the URL it gives you.

**Comment by Dragon911XX** [comment]
Hm. i can't really manage a true transparency, since chromakeying really isn't 100% for me.

**Comment by baffler** [comment]
If you add a Browser source in OBS using the kapchat link I gave you, it will have a completely transparent background. There's no chromakeying required. You shouldn't try to record the program itself, you need to use the Browser source and get the url from https://nightdev.com/kapchat
