### ISSUE TITLE
Can't see channel point redemptions

### ISSUE THREAD

**Issue by brvnda** [baffler/Transparent-Twitch-Chat-Overlay#254]
It use to show my channel point redemptions and now i just cant see it at all. All it shows now is just my chat. I have enabled it in the settings and still wont show.

**Comment by SoloSwain** [comment]
yeah it doing the same thing to me ever since the new version came out it been like this

**Comment by q587p** [comment]
Previous version shows them and current don't, which is sad…

**Comment by q587p** [comment]
In this version channel point redemptions is working (when we setup proper channel id):

[0.9.4](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/0.9.4)

**Comment by baffler** [comment]
This is fixed in [v1.0.4](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.4)
