### ISSUE TITLE
Less of an issue, but more of a question

### ISSUE THREAD

**Issue by MashiroShiinaX** [baffler/Transparent-Twitch-Chat-Overlay#26]
I am currently working on an integrated twitch chat in an application that I am doing, but I couldn't get around the issue to support emotes from every channel on twitch. I even asked on the Twitch API Discord for some help, but they said there isn't a proper way to get all emotes from every channel efficiently. How did you do it?

Best regards,
Mashiro

**Comment by baffler** [comment]
My program uses https://nightdev.com/kapchat so however they do it. You could possibly look into the javascript source and figure out how they do it?
