### ISSUE TITLE
Visible X button above the overlay

### ISSUE THREAD

**Issue by Stefanzoka** [baffler/Transparent-Twitch-Chat-Overlay#268]
![Bez tytułu](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/assets/44088552/87a8aaf9-e913-458d-a30b-2392b0766fa3)
In previous version everything works fine. I downloaded updated version and now i'm seeing "X" buttons when borders are hidden.

**Comment by madruded** [comment]
Same issue here

**Comment by turkeyleg199** [comment]
![Screenshot 2024-04-06 213024](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/assets/166266757/03facc02-2da0-4189-89f6-ec3b37350fd9)

this screenshot shows the "X" and a slight gray background of the overlay, which is not completely clear unfortunately...

**Comment by spin0za** [comment]
Literally unusable.

**Comment by baffler** [comment]
This is fixed in [v1.0.4](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.4)
