### ISSUE TITLE
Want use multiple windows (or process)

### ISSUE THREAD

**Issue by DevCirno** [baffler/Transparent-Twitch-Chat-Overlay#27]
Certain companies use web overlays to show notifications (sponsored, subscribed, followed, hosted, cheered) on the screen, and supports chat display.
I wanted to see both of these great features at the same time, but I couldn't find a solution, so I ask here.

**Comment by baffler** [comment]
Make sure you have the latest version and you can right-click on the title bar (the black bar at top when borders are shown) and click New Window. You can paste any overlay URL into there and it will make the window with the notifications there.

**Comment by DevCirno** [comment]
I didn't know that this function had already been completed. Your program is very much appreciated.
