### ISSUE TITLE
Anti-Virus detects Malware Infection

### ISSUE THREAD

**Issue by Hoko2021** [baffler/Transparent-Twitch-Chat-Overlay#274]
When downloading the setup executable for version 1.0.2. BitDefender places file in quarantine as it detects Gen:Suspicious.Cloud.2. Most likely a false positive but I'd rather open an issue just in case:

![image](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/assets/94189193/1cec8d78-e12f-4e70-81c7-bd6cc7723de2)

Any further information please let me know.

OS: Windows 11

**Comment by Technetium1** [comment]
That's a [generic heuristic detection](https://www.malwarebytes.com/glossary/heuristic-analysis), it isn't actually pointing out a problem. Consider it a false positive, just like this detection in MaxSecure: https://www.virustotal.com/gui/file/3693b0158b9886b2f4b27572d78a28b999539550a6b71b424d87edb992695946
