### ISSUE TITLE
Show the number of viewers!?

### ISSUE THREAD

**Issue by dsanches81** [baffler/Transparent-Twitch-Chat-Overlay#28]
It would be really interesting if we could see how many viewers are now watching your stream.

**Comment by baffler** [comment]
This is possible using any typical OBS widget browser source. For example you can use this: https://streamlabs.com/widgets/viewer-count?token=3E0D3F667D71BE58B05F

Setup the settings on that page on how you want it, make sure to click Save Settings button at the bottom then click Copy for the widget URL.

Go to my app and make sure borders are shown, right-click the black border at top and select New Window. Paste the URL for the widget in the popup box and move the new window to where you want it. Remember to click the "o" button at the top to hide borders for each window you have open. Also this new window will be saved and will launch alongside your chat now.

**Comment by mix3d** [comment]
The "New Window" Setting is clutch. I wonder though if a central "app" hub window would make sense, that you could configure the other overlay windows from, would increase discoverability of TTCO's multi-window functionality.

**Comment by baffler** [comment]
I put a Widget section in the settings now. I think that should help but I do want to eventually have a list of all the windows you have created here that you can add/remove in the settings as well.
