### ISSUE TITLE
Chat: Error Loading Chat: Missing Channel Paramter

### ISSUE THREAD

**Issue by TurtleBoxOfficial** [baffler/Transparent-Twitch-Chat-Overlay#281]
Suddenly stopped working -

**Comment by Randyjones86** [comment]
same here. same message.

**Comment by ShhJebus** [comment]
same as well

**Comment by chrlsfrmg** [comment]
@ShhJebus Don't you know how to fix this? I use all the options of KapChat, like ChatSound, Chat Fade Time, Redemptions, and Theme!
Isn't there a way to fix this?

**Comment by KL4416** [comment]
Same problem, hope it's a temporary thing. Would use the twitch pop out option but I need the sound notification.

**Comment by baffler** [comment]
Can try [v1.0.3](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.3)? Should work now

**Comment by chrlsfrmg** [comment]
> Pode tentar [v1.0.3](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.3) ? Deve funcionar agora

Ok!

**Comment by chrlsfrmg** [comment]
> Pode tentar [v1.0.3](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.3) ? Deve funcionar agora

You're welcome! I'm glad it worked perfectly for you!

**Comment by TurtleBoxOfficial** [comment]
This has worked!
