### ISSUE TITLE
Showing another streams chat

### ISSUE THREAD

**Issue by MichaelHeinzman** [baffler/Transparent-Twitch-Chat-Overlay#282]
I'm trying to use it for my stream but it keeps displaying someone named "night"'s stream chat. Happened today and I had to use my phone instead.

**Comment by MichaelHeinzman** [comment]
My b, just saw the other issues that were related to this one

**Comment by baffler** [comment]
Can try [v1.0.3](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.3)? Should work now
