### ISSUE TITLE
Issue after update 1.0.3

### ISSUE THREAD

**Issue by GennesisX** [baffler/Transparent-Twitch-Chat-Overlay#283]
After the new update, the opacity level is not working. If i set it where i want, when i hide the border, it wont change, and a bar on the bottom of the window shows the change, but not on the entire window.

![image](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/assets/170484038/da57e6ce-0e17-4501-8754-1a87582aaaca)

**Comment by baffler** [comment]
This is fixed in [v1.0.4](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.4)
