### ISSUE TITLE
Point redemption not showing up

### ISSUE THREAD

**Issue by KL4416** [baffler/Transparent-Twitch-Chat-Overlay#285]
Had viewers redeem points but it didn't show up in the chatbox despite having "community point redemptions" box checked. I'm using 1.0.3.

**Comment by baffler** [comment]
I'll have a fix for this in the next version

**Comment by baffler** [comment]
This is fixed in [v1.0.4](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v1.0.4)

**Comment by KorneevVitaly** [comment]
Now it still not showing for some reason
