### ISSUE TITLE
Message highlight

### ISSUE THREAD

**Issue by Project-Kaom** [baffler/Transparent-Twitch-Chat-Overlay#30]
I've noticed that highlighted messages appears as common ones. It would be great to support that in overlay cause sometimes it is easy to miss important messages.

**Comment by baffler** [comment]
I might be able to add this, but can you clarify what you mean by highlighted messages? Is it the point redemption thing?

**Comment by Zariwey0** [comment]
I think it may be this: https://help.twitch.tv/s/article/channel-points-guide?language=en_US

When someone highlights a message (or uses his or her channel points to redeem any reward that implies posting a message), the message appears as a common one, as @Project-Kaom says.

It would be pretty nice if it could look diferent.

**Comment by baffler** [comment]
In [v0.8](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.8) you can use the Twitch popout chat now that will show the redemptions. Just go into Settings, click Chat, and at the bottom-left change it to "Twitch Popout".
