### ISSUE TITLE
Show redemptions in chat? 

### ISSUE THREAD

**Issue by earlbellinger** [baffler/Transparent-Twitch-Chat-Overlay#31]
Twitch has a new feature where users can redeem things with points. These show up in Twitch chat but not in the overlay. Would it be possible to please show these? 

(Along those same lines, follows & subs would also be nice)

**Comment by baffler** [comment]
I need to have some better documentation but basically this functionality is part of the app. Essentially this app works like a Browser source in OBS, so redemptions/follows/subs etc are possible just using typical OBS widgets. For example you can go here: https://streamlabs.com/dashboard#/eventlist

Setup the widget with everything you need (make sure to check the Redemptions checkbox for example) and then click save settings button at the bottom, then copy the Widget URL.

Now just go to my app, make sure to show the borders, and right click the black border at the top, click New Window. Just paste the URL for the widget in the popup box and you should be good to go. It will save this new window and launch it alongside your chat. If you want to remove the window just hit the x on top-right to close it and it will ask if you want to delete the settings for the window, press yes.

**Comment by Zariwey0** [comment]
First of all, thank you for your excelent work.

I can't see any Redemptions checkbox in the url you posted. Besides, I think @earlbellinger is talking about new redemptions from Twitch like highlighting messages.

If I am wrong, ignore this post, haha.

Greetings.

**Comment by jmytch** [comment]
I think he meant the redemption from the Channel Points you redeem on the channel. It should show that redemption in the chat overlay so the streamer is aware when someone redeem like 1,500 points to hydrate etc.

**Comment by baffler** [comment]
In [v0.8](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.8) you can use the Twitch popout chat now that will show the redemptions. Just go into Settings, click Chat, and at the bottom-left change it to "Twitch Popout".
