### ISSUE TITLE
[Feature Request] Notification Sound when a new message appears

### ISSUE THREAD

**Issue by mix3d** [baffler/Transparent-Twitch-Chat-Overlay#32]
I turned to this tool because I keep missing messages from viewers. The overlay is very helpful, but I'm still finding that even onscreen (to the side) I am still missing them showing up. Is it possible to detect a new message and play a sound? I recognize this is a niche feature for small streamers who don't have more than a few people watching at a time though...

**Comment by mix3d** [comment]
Though after reading through the documentation, I don't think the request makes sense here, I'd have to find a web chat url that lets me add sounds. Dang. 

Good app, even if it can't do what I was hoping for!

**Comment by baffler** [comment]
Actually I want to look into this. I have some ideas on how to add it that might work.

**Comment by baffler** [comment]
Was able to get this working. Basically can overwrite some of the javascript that KapChat uses and can play the sound that way. Seems to be working fine and I'll include it in the next version which is coming out soon 👍

**Comment by baffler** [comment]
This feature is in [v0.7](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.7). Check out the settings cause it's not enabled by default and make sure you're not using a Custom URL.

**Comment by mix3d** [comment]
NICE on the feature! Working great, exactly what I needed. (Just took it for a test ride)

Going to suggest a different sound: https://notificationsounds.com/notification-sounds/me-too-603
I went ahead and replaced the alert.wav locally. It's much better.
