### ISSUE TITLE
Volume slider for chat message notification

### ISSUE THREAD

**Issue by SHRMP0** [baffler/Transparent-Twitch-Chat-Overlay#33]
First of all, thank you for this app. The issue title is self-explanatory: I'd like to request you to please add a volume slider for the new chat message notifications

**Comment by baffler** [comment]
Sure, but for now if you want to change the volume just use Windows search and type Sound mixer options and you should be able to turn it down there for the individual app.

**Comment by baffler** [comment]
[v0.9.5](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.9.5) has this feature now 👍
