### ISSUE TITLE
No way to change audio device for alerts?

### ISSUE THREAD

**Issue by Annihilannic** [baffler/Transparent-Twitch-Chat-Overlay#336]
My alerts always go to my speakers but I'd prefer them to go to my headset.

Changing the audio device in Windows seems to be ignored, and I can't see an option in the application... am I missing something?

running v1.0.4 under Windows 10 Pro 22H2

**Comment by baffler** [comment]
It's in the General settings if you scroll down, the Sound Output Device. It should always go through whatever you set as default (assuming the setting in the app is Default), so if you change your audio device to your headset then it should use that. I'll see if it's working properly, but for now you can try changing it manually in the General settings.

**Comment by Annihilannic** [comment]
But there is no.... ah!!  I had installed v1.0.4 but my shortcut was still pointing to 0.91.  :-D
