### ISSUE TITLE
Background Opacity

### ISSUE THREAD

**Issue by Paryn** [baffler/Transparent-Twitch-Chat-Overlay#34]
Hello,

Thank you for the chat overlay. I find it very useful, and so does everyone I suggest it too. One feature I'd like to request is if we could have the ability to change the opacity? For some games/streams it gets a little hard to see the chat. 

Thank you

**Comment by baffler** [comment]
I plan to release v0.71 soonish and I can add this 👍

**Comment by unRyker** [comment]
I thought this could be accomplished with custom CSS?

**Comment by Paryn** [comment]
Yeah my friend and I figured it out not long after I posted that request. I
think we are good :)

**Comment by baffler** [comment]
Custom CSS it's possible but I think it's still good to be able to quickly change it. In [v0.8](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.8) you can right-click the title bar and change opacity that way. The setting will be saved as well.
