### ISSUE TITLE
Code for Custom URL

### ISSUE THREAD

**Issue by jmytch** [baffler/Transparent-Twitch-Chat-Overlay#35]
Do you mind sharing the code again for that custom url thingy for the web captioner? 

I can't seem to find you on the discord to look at our previous conversation >_>

Hope you still have the code as I need them pretty please

**Comment by baffler** [comment]
I opened up my DMs for twitter so you can find me there if you want. But I've been meaning to add something for web captioner so you don't need custom code. I'll look into it and let you know for sure soon.

**Comment by baffler** [comment]
If you add a new widget and it's a webcaptioner link, it will add the code automatically so it has a transparent background. That's available in [v0.8](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.8)

**Comment by baffler** [comment]
Let me know if it works well or looks fine. I can make changes if needed.
