### ISSUE TITLE
Log in as a moderator to bypass chat delay

### ISSUE THREAD

**Issue by taradinoc** [baffler/Transparent-Twitch-Chat-Overlay#36]
One of Twitch's moderation features adds a delay to chat for non-mods, to give moderators time to react to a message before it goes out to viewers.

Since the chat overlay isn't logged in, it's affected by the same delay.

I believe using Twitch's embedded chat as a logged-in user would bypass the delay, giving streamers time to tab over to their dashboard and react to a message before anyone sees it. But even though I can use a custom URL to load Twitch's chat, I don't see a way to log in, since I can't interact with the page.

**Comment by baffler** [comment]
I'll try to get this in for next release. 👍

**Comment by unRyker** [comment]
Please also make sign-in optional too. :)

**Comment by baffler** [comment]
There's a setting in [v0.8](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.8) to let you interact with the browser source now. Just open Settings -> Chat and bottom-left switch it to "Twitch Popout". When borders are show, you should be able to click the Chat button and it will ask you to login.
