### ISSUE TITLE
v0.7 loses settings

### ISSUE THREAD

**Issue by mix3d** [baffler/Transparent-Twitch-Chat-Overlay#37]
Seems like when I close the app, some of my settings disappear and get reset. 

Chat fade on/off, chat fade timeout, and notification sound toggle, are all being reset when I reboot my computer without closing TTCO first.

**Comment by baffler** [comment]
This will be fixed in next version. Thanks 👍

**Comment by baffler** [comment]
This should be fixed now in [v0.8](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.8)
