### ISSUE TITLE
Appears as an opaque black rectangle in stream

### ISSUE THREAD

**Issue by Flob368** [baffler/Transparent-Twitch-Chat-Overlay#41]
![Screenshot (147)](https://user-images.githubusercontent.com/71211024/93015161-7f319e80-f5b7-11ea-8d72-75dc662cfe22.png)
![Screenshot (148)](https://user-images.githubusercontent.com/71211024/93015162-8193f880-f5b7-11ea-9d0d-120ef22d944f.png)

The app in itself works fine, but whenever I try to capture it using OBS it just appears as an opaque black rectangle. When it is the focused window it even shows a trail of the position of the mouse over it that doesn't seem to disappear until I hide the capture and show it again.

**Comment by pesnitor** [comment]
Having the same issue. Did you manage to solve it? @Flob368

**Comment by baffler** [comment]
If you do Window Capture and change the capture method to "Windows Graphics Capture" then it seems to sorta work. It sorta works cause there's no transparency. If you want to put chat on your OBS there's a lot of ways to do it that is better. You can use the same website the app uses https://nightdev.com/kapchat and just add it as a browser source to your OBS.
