### ISSUE TITLE
Crashes on first load

### ISSUE THREAD

**Issue by m0nkid** [baffler/Transparent-Twitch-Chat-Overlay#45]
Whenever I start the overlay for the first time after a Windows reboot it crashes.

After re-launching the overlay for a second time it works fine.

> An unhandled exception occured. Note you can click on this message box to focus it, then press Ctrl-C to copy the entire message.
> 
> System.Exception: Unable to execute javascript at this time, scripts can only be executed within a V8Context. Use the IWebBrowser.CanExecuteJavascriptInMainFrame property to guard against this exception. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#when-can-i-start-executing-javascript for more details on when you can execute javascript. For frames that do not contain Javascript then no V8Context will be created. Executing a script once the frame has loaded it's possible to create a V8Context. You can use browser.GetMainFrame().ExecuteJavaScriptAsync(script) or browser.GetMainFrame().EvaluateScriptAsync to bypass these checks (advanced users only).
> 
>    bei CefSharp.WebBrowserExtensions.ExecuteScriptAsync(IWebBrowser browser, String script)
> 
>    bei TransparentTwitchChatWPF.MainWindow.InsertCustomCSS(String CSS)
> 
>    bei TransparentTwitchChatWPF.MainWindow.Browser1_LoadingStateChanged(Object sender, LoadingStateChangedEventArgs e)
> 
>    bei CefSharp.Wpf.ChromiumWebBrowser.CefSharp.Internals.IWebBrowserInternal.SetLoadingStateChange(LoadingStateChangedEventArgs args)
> 
>    bei CefSharp.Internals.ClientAdapter.OnLoadingStateChange(ClientAdapter* , scoped_refptr<CefBrowser>* browser, Boolean isLoading, Boolean canGoBack, Boolean canGoForward)

**Comment by baffler** [comment]
I'll try to get a fix for this in next version, thanks.

**Comment by m0nkid** [comment]
Confirmed fixed, thanks.
