### ISSUE TITLE
i cant find the exe file

### ISSUE THREAD

**Issue by aidan-tan** [baffler/Transparent-Twitch-Chat-Overlay#51]
like, i download the whole thing as a zip, and the exe file isnt in there

**Comment by funcelot** [comment]
> like, i download the whole thing as a zip, and the exe file isnt in there

did you use antivirus software? Norton may seen zip content way beoyond you can do it, protecting you from running malicous executables

**Comment by baffler** [comment]
You made need to add an exception for the app with your antivirus. The other thing I'd say to try is just using the installer, it will add a shortcut for you on your desktop and such.
