### ISSUE TITLE
[Feature Request] Linux Version

### ISSUE THREAD

**Issue by Toadfield** [baffler/Transparent-Twitch-Chat-Overlay#52]
I am a Linux gamer and I don't know any other program.

**Comment by darkralts** [comment]
same, this program looks so nice, i would love this on linux as well

i dont think it would be too hard to make dotnet work on linux with mono, but im not a coder so i have no idea

**Comment by darkralts** [comment]
https://github.com/danieloneill/TwitchOverlay
this is the closest program i could find that has a linux version, im gonna try it out and see if it works for me, but i dont really like the look of it, and this program has exactly what im looking for :D looks like the OG twitch chat

**Comment by Toadfield** [comment]
If it works can you tell me how you installed it?
Cause I never install programs that are not available in my package manager,so I don't know how.
And is it actually better than using an transparent window of the twitch chat in the web?
Cause if not I will just use the web version.
But even if it's good,without updates or forks it isn't possible to add cool features.

**Comment by darkralts** [comment]
yeah, i never managed to get this one to work either unfortunately, it might work for you but basically what i did was download and extract it, and i ran the executable through the terminal, which you can do by ./path-to-file

**Comment by darkralts** [comment]
although, if youre still looking for a solution, i found something called restream, while i dont really like it it seems like the only option i have for right now sadly, heres a link
https://restream.io/

if mr autor man is reading this, i would greatly appreciate this as im sure many other linux twitch streamers would aswell :D

**Comment by Toadfield** [comment]
For Restream,is it open source?
Cause if not,I won't use it.

**Comment by mrpajax** [comment]
Hi @Toadfield, @darkralts ,
Restream.io isn't an open-source project.

TTCO (short repo's name) uses a lot of Windows libraries, unfortunately, create port isn't available by change a few lines of codes.

**Comment by darkralts** [comment]
Aw that's unfortunate to hear, thanks for the reply though :D and yeah,
unfortunately restream is proprietary, it's the only workable solution I
found for this sort of thing, maybe I'll take the plunge and learn coding
and make my own, I highly doubt I could even get to that level, but I guess
I could at least try :D
