### ISSUE TITLE
Custom CSS not working for trovo chat

### ISSUE THREAD

**Issue by dule333** [baffler/Transparent-Twitch-Chat-Overlay#53]
I tried to setup the trovo chat in this, but the custom CSS i used doesn't apply. The CSS works in OBS, but not here. Any ideas?
![image](https://user-images.githubusercontent.com/22330512/99903229-659d8900-2cc3-11eb-96c5-2374d993a729.png)

**Comment by baffler** [comment]
I got a fix for this that will be in the next release. 👍

**Comment by baffler** [comment]
Can you try it with [v0.8.1](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.8.1)?

**Comment by dule333** [comment]
Yep, that fixed it. It works properly now. Thanks
