### ISSUE TITLE
System.Exception: The browser has not been initialized. Load can only be called after the underlying CEF browser is initialized

### ISSUE THREAD

**Issue by GodSponge** [baffler/Transparent-Twitch-Chat-Overlay#57]
I am getting this error on the new 0.8.1. I attached the full error message.

Reverting to 0.8 does not throw this error.

[error.txt](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/files/5651664/error.txt)

_Originally posted by @GodSponge in https://github.com/baffler/Transparent-Twitch-Chat-Overlay/issues/38#issuecomment-739785639_

**Comment by baffler** [comment]
[v0.91](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.91) should have fixed this issue. Try it and let me know 👍

**Comment by GodSponge** [comment]
As far as I can tell the issue is gone. I have not seen any crashes since I installed v0.91
