### ISSUE TITLE
Twitch chat not connecting to channel

### ISSUE THREAD

**Issue by White12ose** [baffler/Transparent-Twitch-Chat-Overlay#6]
Hello I love this chat add on and have used it since I started streaming. Today I started it up and it does not want to connect to my stream chat. I can use the custom link url but its not transparent like it is when I just have it connected to my stream chat name. I have tried uninstalling it and reinstalling it and restarting my computer, no matter how many times I try to set the channel name it will not connect and work.

**Comment by baffler** [comment]
Make sure you right click the taskbar icon and choose "Set Channel" and only put your twitch username in this field. You should only have to do this once and it will save the setting. If the chat doesn't sometimes, it could be an issue with Twitch itself and you may want to try launching the program later to see if the chat is restored on their end.
