### ISSUE TITLE
Overlay does not honour windows 10 sound device settings

### ISSUE THREAD

**Issue by arronhuk** [baffler/Transparent-Twitch-Chat-Overlay#64]
The overlay always plays sounds with whatever the default device is set to by windows when it starts, I set the app specific sound option in windows for the overlay to a separate device (so it doesn't get picked up on stream) but it still uses the default device.

The workaround is to set a default sound device , start the app, change the default device back and start everything else but would be great if it would honour the settings
 
![image](https://user-images.githubusercontent.com/9217331/104111846-37a9ed80-52df-11eb-87c3-a840f4da153d.png)

**Comment by baffler** [comment]
I think this is because of the particular sound library I'm using to play sounds, which I've been meaning to update anyways. I wasn't aware of this problem, so when I change the sound library, I'll make sure it lets you switch the device 👍

**Comment by DerLuemmel** [comment]
> I think this is because of the particular sound library I'm using to play sounds, which I've been meaning to update anyways. I wasn't aware of this problem, so when I change the sound library, I'll make sure it lets you switch the device 👍

That would be so great! Thank you.

**Comment by baffler** [comment]
[v0.9.5](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.9.5) has this feature now.. finally!
