### ISSUE TITLE
Bug in Kapchat?

### ISSUE THREAD

**Issue by f3noxy** [baffler/Transparent-Twitch-Chat-Overlay#73]
It just doesn't load the chat anymore, I think it's a bug on Kapchat, can anyone confirm?
![image](https://user-images.githubusercontent.com/78822853/107423161-c9816200-6afa-11eb-9b93-e6f444b9926d.png)

**Comment by baffler** [comment]
Not having that issue. Sometimes twitch chat just breaks, could it have been down? Also, try going to https://nightdev.com/kapchat/ and testing it there as well, see if it works in a browser.

**Comment by f3noxy** [comment]
I discovered how to fix it, basically it was a certificate problem on the website hosting jQuery, that is used in KapChat.
![image](https://user-images.githubusercontent.com/78822853/107463626-49302080-6b3d-11eb-820e-0b500484413f.png)
this one to be more exact, because of that KapChat couldn't work properly, but I changed my DNS to google's (8.8.8.8 and 8.8.4.4) and it worked.

(sorry for any english mistakes, i'm still learning.)
