### ISSUE TITLE
2 Issues - A crash and Top message in chat is always faded out regardless of settings

### ISSUE THREAD

**Issue by zepaladin** [baffler/Transparent-Twitch-Chat-Overlay#74]
Issue 1 - Top message in chat is always half-faded out, regardless of whether I have the "fade out old chat lines" option toggled. Not that it should matter because it's not an old message anyway. 
![issue](https://user-images.githubusercontent.com/78828642/107456130-90bbaa00-6b47-11eb-83a7-afe5b622c67a.JPG)
![issue2](https://user-images.githubusercontent.com/78828642/107456144-96b18b00-6b47-11eb-9d3a-f015d62b81e1.JPG)

In this case, it's a system message, but it happens with regular chat messages as well.

2 -  "An unhandled exception occurred. Click on this message box and press Ctrl-C to copy the entire message"
I've closed the box in the meantime and forgot to copy, but it was like 50 strings of text, cant really remember what they said.
worthy of note just before the unhandled exception thing happened I noticed heavy microstutter in the game I was playing (in this case Division 2)

This whole project has a lot of potential for people who, like me, only have a single monitor. Good luck with it!

**Comment by baffler** [comment]
The fading of the top line is due to the Theme you chose in the settings. It's just setup that way, you can try choosing a different theme if you want. For the error, I'd need to see it to know what the problem is.
