### ISSUE TITLE
Hello I have a question

### ISSUE THREAD

**Issue by minbeomi** [baffler/Transparent-Twitch-Chat-Overlay#76]
I am a user who enjoys using this application.

this app are simple, simple, and easy to access.

I've been using this application well until a few months ago, and every time I turn on this application and lol it, I've been using it well.
The frame is fixed at 60. If you turn it off, the frame will double.

What is the reason for the frame decline?

**Comment by batatolol** [comment]
I have the same problem after updating Windows 10.

Not running the application, League of Legends runs in 200 FPS.
Running the application, it runs in 80 FPS
