### ISSUE TITLE
Unable to access settings menu on Windows 10

### ISSUE THREAD

**Issue by lisushka** [baffler/Transparent-Twitch-Chat-Overlay#8]
Hello,

I'm trying to use this tool on Windows 10, version 1803.  When I right-click on the tray application, I do not get a Settings option, I only get Pin to Taskbar and Close Window.  I have tried re-downloading and extracting.

This is what I see when I open the application menu in the tray.
![image](https://user-images.githubusercontent.com/28942094/47759173-76f15280-dd02-11e8-971c-756c286d314e.png)

**Comment by facialhairs** [comment]
Yeah i thought i was crazy couldnt find a way for it to work sad though its a nice app i also have windows 10.

**Comment by facialhairs** [comment]
I think it would be easier if you could type the twitch account in a file instead of having to get some settings from the task bar.

**Comment by baffler** [comment]
The tray icon will be the area next to the clock on the taskbar. That area in screenshot is not the right spot. Try clicking the ^ arrow next to the clock and you should see it. I have a new version in the works, I'll try to put the settings in a more obvious location for next release.

**Comment by baffler** [comment]
In v0.6, settings are easier to access now, and there's a settings window now. You can also access the settings or toggle borders by right-clicking the icon in the taskbar, like the way you were doing it in your screenshot.
