### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by dunof** [baffler/Transparent-Twitch-Chat-Overlay#9]
Hello Friend!
Its program is very cool and mainly very useful ... Without doubts it helps the life of those who have only one monitor or small monitors. Thank you very much for developing it!

Could you please let me know if there is any way to change the type, and especially the font size?

Thanks again!

**Comment by LordPinkerton** [comment]
I second this. Also, the ability to turn off an on badges and change font color.

**Comment by baffler** [comment]
Font size can be changed by zooming, in v0.6 you can right-click the black border at the top and change the zoom level. If you want to change font (also font size is possible) you can do custom css. Just go into the settings and for theme choose "None". You would be able to change the color and other properties (possibly hide the badges, didn't look into that). CSS is a bit more advanced, so I might try to implement this an easier way in the future.

**Comment by baffler** [comment]
> I second this. Also, the ability to turn off an on badges and change font color.

https://streamlabs.com/dashboard#/chatbox

This chat widget lets you turn off badges and a lot of other options. You can use it as a custom URL in my app.
