### ISSUE TITLE
Cannot access options menu if both taskbar icon and window border is hidden

### ISSUE THREAD

**Issue by cawong89** [baffler/Transparent-Twitch-Chat-Overlay#91]
In the options, I hid the taskbar icon as well as the borders of the window. Now the overlay is a transparent chat that I cannot interact with, and there is no way to interact with the program anymore, including accessing settings.

When I right click the application in the taskbar, this is all I see: 

![image](https://user-images.githubusercontent.com/4325736/120948448-10711400-c6f7-11eb-9163-afa7b348fd03.png)

And the chat overlay itself has no borders so it no longer has the little buttons to change anything. Thus there is no way to interact with the program anymore, and this persists after restarting the application.

**Comment by baffler** [comment]
Yeah that's an issue ha, probably will have to make sure you can't disable both of those options.

**Comment by baffler** [comment]
[v0.91](https://github.com/baffler/Transparent-Twitch-Chat-Overlay/releases/tag/v0.91) should fix this for you. I made it so the system tray icon is always active.
